# Generated by Django 3.2.3 on 2021-05-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.BooleanField(default=False, null=True, verbose_name='Подтверждение пользователя')),
                ('photo', models.ImageField(blank=True, default='default_profil.jpg', null=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар пользователя')),
                ('vkontakte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль пользователя Git')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
