# Generated by Django 3.2.3 on 2021-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vkontakte',
            new_name='git',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль пользователя Telegram'),
        ),
    ]
