# Generated by Django 3.2.3 on 2021-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_auto_20210528_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_team',
            field=models.BooleanField(default=False, null=True, verbose_name='Поиск команды'),
        ),
    ]
