# Generated by Django 3.2.3 on 2021-05-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0003_profile_search_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='group_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuser.group', verbose_name='Группа'),
        ),
    ]
