# Generated by Django 3.2.3 on 2021-05-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='profile',
            name='team_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileuser.team', verbose_name='Команда'),
        ),
    ]
