# Generated by Django 3.2.3 on 2021-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20210529_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon/%Y/%m/%d', verbose_name='Обложка Хакатона'),
        ),
    ]
