# Generated by Django 3.2.3 on 2021-05-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Команда')),
                ('team_verification', models.BooleanField(default=False, null=True, verbose_name='Подтверждение команды')),
                ('team_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.hackathon', verbose_name='Кейс для команды')),
                ('user_teams', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.BooleanField(default=False, null=True, verbose_name='Подтверждение пользователя')),
                ('search_team', models.BooleanField(default=False, null=True, verbose_name='Поиск команды')),
                ('photo', models.ImageField(blank=True, default='default_profil.jpg', null=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар пользователя')),
                ('bio', models.TextField(blank=True, default='Hello World!', null=True, verbose_name='Биография')),
                ('git', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль пользователя Git')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль пользователя Telegram')),
                ('group_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_user.group', verbose_name='Группа')),
                ('tags', models.ManyToManyField(blank=True, to='profile_user.Tag', verbose_name='Теги пользователя')),
                ('team_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_user.team', verbose_name='Команда')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
