# Generated by Django 3.2.3 on 2021-05-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_user', '0002_auto_20210529_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_capitan', to=settings.AUTH_USER_MODEL, verbose_name='Капитан команды'),
        ),
    ]
