# Generated by Django 3.2.3 on 2021-05-29 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_user', '0003_alter_team_capitan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_user.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_teams',
            field=models.ManyToManyField(blank=True, related_name='test', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
    ]
