# Generated by Django 3.2.3 on 2021-05-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_auto_20210529_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_user.team', verbose_name='Команда'),
        ),
    ]
