# Generated by Django 3.2.3 on 2021-05-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_user', '0005_alter_profile_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_user.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_teams',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
    ]
