# Generated by Django 3.2.3 on 2021-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_auto_20210529_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=70, null=True, verbose_name='Ссылка на группу'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=70, null=True, verbose_name='Ссылка на команду участника'),
        ),
    ]
