# Generated by Django 3.2.3 on 2021-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0007_auto_20210530_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estimation_user',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Оценка за текущей хакатон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Балы организатора или спонсора'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_user',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Глобальный рейтинг пользователя'),
        ),
        migrations.AddField(
            model_name='team',
            name='estimation_team',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Оценка за текущей хакатон'),
        ),
        migrations.AddField(
            model_name='team',
            name='rating_team',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Глобальный рейтинг команды'),
        ),
    ]
